# Generated by Django 5.0.7 on 2024-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=60466678305820275064052241349345836510, unique=True),
        ),
    ]
