# Generated by Django 5.0.7 on 2024-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=74840050022149978227722836304260202544, unique=True),
        ),
    ]
