# Generated by Django 5.0.7 on 2024-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0036_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=86619225707480011486339259548144367112, unique=True),
        ),
    ]
