# Generated by Django 5.0.7 on 2024-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0037_alter_user_fidc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farmarea',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farmlandmarks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farmname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fidc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
