# Generated by Django 5.0.7 on 2024-07-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0040_alter_user_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True),
        ),
    ]
