# Generated by Django 5.0.7 on 2024-07-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0042_user_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quizes',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
