# Generated by Django 5.0.7 on 2024-07-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0044_alter_user_quizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quizes',
            field=models.JSONField(default={}),
        ),
    ]
